import { Icon }  from 'antd'

// 参考 https://3x.ant.design/components/icon/#Custom-Font-Icon  // generated by iconfont.cn
export const MyIcon = Icon.createFromIconfontCN({
    scriptUrl : 
		'//at.alicdn.com/t/font_1663760_3gd0hideasn.js'
});


